behaviors:
  playerMLAgent:
    trainer_type: ppo
    max_steps: 5.0e8
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.1
        gamma: 0.99
        use_actions: true
        demo_path: Demos/PlayerCoward.demo
      curiosity:
        strength: 0.02
        gamma: 0.99
    #behavioral_cloning:
      #strength: 0.5
      #steps: 500000
      #demo_path: Demos/PlayerCoward.demo